### ISSUE TITLE
AmazonAdsEvent doesn't give any information about the Amazon Ad

### ISSUE THREAD

**Issue by KDApps** [digicrafts/AmazonAds-ANE#2]
I use your ANE and i love it, but if no ads were available from the Amazon Mobile Ad Network, then i wanna show them from Admob.

Can you maybe tell me how i can fix this or can you maybe fix it for me?

Thank you very much.

Kind regards,
Developer KDApps

**Comment by tsangwailam** [comment]
This ANE only dedicated to Amazon Ads. You may need other ANE if you like to show Admob ads. You can make use of the InterstitialAdFailedToLoad event to check if you amazon ads can load. Else, load the admob ads. 

You can try the https://github.com/Code-Alchemy/AdMobAne for admob.
