### ISSUE TITLE
Do you maybe update the ANE with the new AmazonAds SDK?

### ISSUE THREAD

**Issue by KDApps** [digicrafts/AmazonAds-ANE#4]
I got an email about the new version of the AmazonAds SDK. Will you maybe update your great ANE with the new version of the SDK?

For more info: https://developer.amazon.com/public/apis/earn/mobile-ads/docs/release-notes

Thank you very much.

Developer KDApps

**Comment by tsangwailam** [comment]
We just update to newest version SDK 5.4. You can try if any problem.
