### ISSUE TITLE
Use AmazonAds-ANE with flashDevelop

### ISSUE THREAD

**Issue by badjem79** [digicrafts/AmazonAds-ANE#5]
as the title says, i have no luck using this ANE with Flashdevelop
if i set the imported lib as "External Library" i get the error:
Variable digicrafts.extensions::AmazonAds is not defined.
while i call

``` javascript
AmazonAds.setAppKey
```

instead if i set the lib as "Include reference classes"
the error is: Cannot access a property or method of a null object reference
at line 54 of src/digicrafts/extensions/AmazonAds.as

any idea on how to setup the library in the correct way for Flashdevelop

thanks

**Comment by tsangwailam** [comment]
Since i am not familiarise with Flash Develop. I can't exactly tell if you miss something. But likely you didn't package the ane into your apps.

You may try follow the tutorial here to add a ane.
http://fermmm.wordpress.com/2014/01/04/working-tutorial-to-install-air-native-extensions-in-flash-develop-4-windows-desktop-project/

**Comment by badjem79** [comment]
That made the trick , it is working now in the Android Emulator, anyway it is giving me an error in the desktop emulator:

Error #3500: The extension context does not have a method with the name setAppKey.

I thougth it would fall back gracefully, but i will use 2 try catch and it is better than nothing.

Thank you very much!

## 

Fabio

**Comment by badjem79** [comment]
Actually I did something like this:
            if(flash.system.Capabilities.version.indexOf('WIN') == -1) {
                AmazonAds.setAppKey("74a4803df76d420baf55de64f0a90322", false);
            }
            if(flash.system.Capabilities.version.indexOf('WIN') == -1) {
                AmazonAds.showAdView('banner_name');
            }
...

**Comment by tsangwailam** [comment]
@badjem79 it will not work on emulator. It only support real device.
